server:
  port: 7002

springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method

spring:
  datasource:
    url: jdbc:mysql://localhost:3309/spring_chatting
    username: root
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

token:
  secret-key: "SECRET"
  refresh-secret-key: "REFRESH_SECRET"
  token-time: 300
  refresh-token-time: 300
